package com.muffar.daymeal.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF7D5800)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDEA9)
val md_theme_light_onPrimaryContainer = Color(0xFF271900)
val md_theme_light_secondary = Color(0xFF006590)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC8E6FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2F)
val md_theme_light_tertiary = Color(0xFF4D6543)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCFEBC0)
val md_theme_light_onTertiaryContainer = Color(0xFF0B2006)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFEEE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4E4639)
val md_theme_light_outline = Color(0xFF807667)
val md_theme_light_inverseOnSurface = Color(0xFFF8EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFBA27)
val md_theme_light_surfaceTint = Color(0xFF7D5800)
val md_theme_light_outlineVariant = Color(0xFFD1C5B4)
val md_theme_light_scrim = Color(0xFF000000)